--
-- Remote Laboratory Framework
--
-- by Carlos A. Rodríguez Mecha
--
-- Elimina el contenido de la base de datos.
-- v0.1
--

DROP PROCEDURE IF EXISTS authAdmin;
DROP PROCEDURE IF EXISTS emergency;
DROP PROCEDURE IF EXISTS toolKey;
DROP PROCEDURE IF EXISTS droptool;
DROP PROCEDURE IF EXISTS startlab;
DROP PROCEDURE IF EXISTS stoplab;
DROP PROCEDURE IF EXISTS armlab;
DROP PROCEDURE IF EXISTS disarmlab;
DROP PROCEDURE IF EXISTS timeout;


DROP PROCEDURE IF EXISTS accesstoken;
DROP PROCEDURE IF EXISTS usetoken;
DROP PROCEDURE IF EXISTS loginClient;
DROP PROCEDURE IF EXISTS logoutClient;
DROP PROCEDURE IF EXISTS status;
DROP PROCEDURE IF EXISTS definitions;
DROP PROCEDURE IF EXISTS takeTool;
DROP PROCEDURE IF EXISTS usedTools;


DROP TRIGGER IF EXISTS ins_user;


DROP TABLE IF EXISTS registry;
DROP TABLE IF EXISTS action_parameter;
DROP TABLE IF EXISTS socket;
DROP TABLE IF EXISTS parameter;
DROP TABLE IF EXISTS action;
DROP TABLE IF EXISTS constant;
DROP TABLE IF EXISTS tool;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS lab;


